name: Deploy to Vercel

on:
  push:
    branches:
      - main   # or 'master', your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build project
      - name: Build project
        run: npm run build

      # 5. Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}   # your Vercel token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # your Vercel org ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # your project ID
          working-directory: .   # root directory
          prod: true
